# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
# datasources:
#   - name: PostgreSQL
#     type: postgres
#     access: proxy
#     url: db:5432
#     database: nyc-taxi
#     user: postgres
#     secureJsonData:
#       password: 'example'
#     jsonData:
#       sslmode: 'disable'


# datasources:
#   - name: PostgreSQL
#     type: postgres
#     access: proxy
#     url: db:5432
#     user: postgres
#     secureJsonData:
#       password: 'example'
#     jsonData:
#       sslmode: 'disable'
#       database: test


datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
      database: metrics_store

